### ISSUE TITLE
Can't plot burgers_equation and wave_equation PINN

### ISSUE THREAD

**Issue by todowede** [madagra/basic-pinn#2]
Hello @madagra,
thanks so much for this code and your blog post on PINN. 
I'm having problem running the codes for `burgers_equation_1d.py` and `wave_equation_1d.py`.  It trains completely but got stuck at "Plot". I was however able to run the `logistic_equation_1d.py` code and that plot ok.

DO you any reason for this. Thanks

**Comment by madagra** [comment]
Burgers and wave equation solutions have been removed after the upgrade to the functional API. They will be soon reintroduced in the code with plotting included. Stay tuned!
