### ISSUE TITLE
BUG; I am getting an error message on Solving the differential equation with PINNs part

### ISSUE THREAD

**Issue by ChidiOkoene** [madagra/basic-pinn#5]
I decided to run the sample codes on the article as I was read and I got an error message on the Solving the differential equation with PINNs part, below is the complete error track

{
	"name": "NameError",
	"message": "name 'params_dict' is not defined",
	"stack": "---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[9], line 20
     17 x = torch.FloatTensor(batch_size).uniform_(domain[0], domain[1])
     19 # compute the loss with the current parameters
---> 20 loss = loss_fn(params, x)
     22 # update the parameters with functional optimizer
     23 params = optimizer.step(loss, params)

Cell In[5], line 8, in loss_fn(params, x)
      5 def loss_fn(params: torch.Tensor, x: torch.Tensor):
      6 
      7     # interior loss
----> 8     f_value = f(x, params)
      9     interior = dfdx(x, params) - R * f_value * (1 - f_value)
     11     # boundary loss

Cell In[4], line 9, in f(x, params)
      8 def f(x: torch.Tensor, params: dict[str, torch.nn.Parameter]) -> torch.Tensor:
----> 9     return functional_call(model, params_dict, (x, ))

NameError: name 'params_dict' is not defined"
}

Can I get an explanation and possible way to go about the bug

**Comment by madagra** [comment]
I am closing this one since the code is now fully functional. You can run it for both logistic and wave equations using the instructions in the README file.
